### PR TITLE
mino60 updates

### PR DESCRIPTION
**Pull request by biko-73**
new updates 
https://www.linuxsat-support.com/thread/142677-plugin-subssupport/?postID=747860#post747860

### CODE REVIEW

**Comment by biko-73** [comment]
new updates are uploaded

**Comment by biko-73** [comment]
new updates are uploaded

**Comment by mx3L** [comment]
Hi, PR is finished can I merge it?

**Comment by mx3L** [comment]
Please let me know if author of the PR mino60 wants to have access and has a github account I can add him so he can freely continue in updating the plugin in here without my assistance.

**Comment by biko-73** [comment]
I send to him to contact directly,
Waiting for his response
I think he haven't github account

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mx3L** [comment]
ok, thank you

**Pull request merged**
